#server host
config:
  server:
    ip: 192.168.232.135

#spring config
spring:
  application:
    name: MMCMS
  datasource:
    url: jdbc:mysql:// ${config.server.ip}:3306/mmcms?useUnicode=true&characterEncoding=utf-8
    username: zhouchong
    password: zhouchong@510
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      port: 27017
      database: cms
      host: ${config.server.ip}
  redis:
    host: ${config.server.ip}
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8

  cache:
    redis:
      key-prefix: ${spring.application.name:application}
      cache-null-values: false


# spring server config
server:
  port: 80
  servlet:
    context-path: /cms

#logging config
logging:
  file: ./logs/cms.log
  level:
    root: info

#用户登录Redis过期时间
com:
  cloudminds:
    user:
      token:
        ttl: 1800

