#spring config
spring:
  application:
    name: MMCMS
  datasource:
    url: jdbc:mysql://192.168.232.129:3306/mmcms?useUnicode=true&characterEncoding=utf-8
    username: zhouchong
    password: zhouchong@510
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
#      host: 10.11.34.173\
      port: 27017
      database: cms
      host: 192.168.232.129

# spring server config
server:
  port: 80
  servlet:
    context-path: /cms

#logging config
logging:
  file: ./logs/cms.log
  level:
    root: info

#用户登录Redis过期时间
com:
  cloudminds:
    user:
      token:
        ttl: 1800

